// <auto-generated />
namespace Trello_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addusercard : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addusercard));
        
        string IMigrationMetadata.Id
        {
            get { return "202511030738343_add-usercard"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
